# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSU103():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.FIREFOX)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_sU103(self):
    self.driver.get("http://localhost:8081/projects?page=1")
    self.driver.set_window_size(1120, 680)
    self.driver.find_element(By.CSS_SELECTOR, ".ls-projects-page__link:nth-child(4) .ls-project-card__title svg").click()
    self.driver.find_element(By.LINK_TEXT, "Settings").click()
    self.driver.find_element(By.LINK_TEXT, "Instructions").click()
    self.driver.find_element(By.NAME, "expert_instruction").click()
    self.driver.find_element(By.NAME, "expert_instruction").click()
    element = self.driver.find_element(By.NAME, "expert_instruction")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.NAME, "expert_instruction").send_keys("Xem thong tin")
    self.driver.find_element(By.CSS_SELECTOR, ".ls-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ls-breadcrumbs__item:nth-child(2) .ls-breadcrumbs__label").click()
    self.driver.find_element(By.CSS_SELECTOR, ".dm-table__cell:nth-child(7) > div").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".ls-button:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ls-modal__body").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".ls-modal__body > div").text == "Xem thong tin"
  
