# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSU43():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.FIREFOX)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_sU43(self):
    self.driver.get("http://localhost:8081/projects/?page=1")
    self.driver.set_window_size(714, 680)
    element = self.driver.find_element(By.CSS_SELECTOR, ".ls-projects-page__link:nth-child(2) .ls-project-card__header")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".ls-button_size_compact").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ls-toggle-items__item:nth-child(2) > .ls-create-project__tab").click()
    self.driver.find_element(By.NAME, "url").click()
    self.driver.find_element(By.NAME, "url").click()
    self.driver.find_element(By.NAME, "url").send_keys("https://toigingiuvedep.vn/wp-content/uploads/2021/05/anh-xe-dap-dep-doc-da-820x513.jpg")
    self.driver.find_element(By.CSS_SELECTOR, ".ls-upload_page__url-form > button").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".ls-upload_page__error").text == "[7b85f398-3e31-459c-a316-b26631c9fb86] Validation error (HTTP Error 404: Not Found)"
  
