# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSU44():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.FIREFOX)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_sU44(self):
    self.driver.get("http://localhost:8081/projects/?page=1")
    self.driver.set_window_size(714, 680)
    self.driver.find_element(By.CSS_SELECTOR, ".ls-button_size_compact").click()
    self.driver.find_element(By.ID, "project_name").click()
    self.driver.find_element(By.ID, "project_name").send_keys("demo")
    self.driver.find_element(By.CSS_SELECTOR, ".ls-toggle-items__item:nth-child(2) > .ls-create-project__tab").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ls-upload_page__upload-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ls-button:nth-child(2)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "td:nth-child(1)").text == "upload/37/61d4e80f-hinh-anh-nhung-chu-cho-de-thuong-nhat.jpg"
  
