# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSU41():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.FIREFOX)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_sU41(self):
    self.driver.get("http://localhost:8081/projects/?page=1")
    self.driver.set_window_size(714, 680)
    self.driver.find_element(By.CSS_SELECTOR, ".ls-button_size_compact").click()
    self.driver.find_element(By.ID, "project_name").click()
    self.driver.find_element(By.ID, "project_name").send_keys("demo_test")
    self.driver.find_element(By.ID, "project_description").click()
    self.driver.find_element(By.ID, "project_description").send_keys("Thực hiện demo Test")
    self.driver.find_element(By.CSS_SELECTOR, ".ls-button:nth-child(2)").click()
  
