# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

# Khởi tạo trình duyệt WebDriver (ví dụ: Chrome)
driver = webdriver.Chrome()
wait = WebDriverWait(driver, 10)

driver.get("http://labelstudio-env.eba-zbadmmg2.ap-southeast-2.elasticbeanstalk.com/user/login/")

# nhập email
email_input = driver.find_element(By.ID, "email")
email_input.send_keys("20110753@student.hcmute.edu.vn")
#nhập pass
pass_input = driver.find_element(By.ID, "password")
pass_input.send_keys("Thuytrang0304@")


register_button = driver.find_element(By.XPATH, "//button[text()='Log in']")
register_button.click()

# Kiểm tra thông báo lỗi

# Đóng trình duyệt
driver.quit()

  
