# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSU21():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.FIREFOX)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_sU21(self):
    self.driver.get("http://localhost:8081/user/login/")
    self.driver.set_window_size(1280, 680)
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("20110753@student.hcmute.edu.vn")
    self.driver.find_element(By.CSS_SELECTOR, ".ls-button").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".error").text == "The email and password you entered don\\\'t match. "
  
