# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSU111():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.FIREFOX)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_sU111(self):
    self.driver.get("http://localhost:8081/projects/?page=1")
    self.driver.set_window_size(1120, 680)
    self.driver.find_element(By.CSS_SELECTOR, ".ls-projects-page__link:nth-child(2) .ls-project-card__title svg").click()
    self.driver.find_element(By.LINK_TEXT, "Settings").click()
    self.driver.find_element(By.LINK_TEXT, "Cloud Storage").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ls-columns__item:nth-child(1) .ls-button").click()
    self.driver.find_element(By.NAME, "title").click()
    self.driver.find_element(By.NAME, "title").send_keys("demo")
    self.driver.find_element(By.NAME, "bucket").click()
    self.driver.find_element(By.NAME, "bucket").send_keys("nhom12")
    self.driver.find_element(By.NAME, "regex_filter").click()
    self.driver.find_element(By.NAME, "regex_filter").send_keys(".*")
    self.driver.find_element(By.NAME, "region_name").click()
    self.driver.find_element(By.NAME, "region_name").click()
    self.driver.find_element(By.NAME, "region_name").click()
    self.driver.find_element(By.NAME, "region_name").send_keys("us-east-1")
    self.driver.find_element(By.NAME, "s3_endpoint").click()
    self.driver.find_element(By.NAME, "aws_access_key_id").send_keys("Thuytrang0304@")
    self.driver.find_element(By.NAME, "s3_endpoint").send_keys("20110753@student.hcmute.edu.vn")
    self.driver.find_element(By.CSS_SELECTOR, ".ls-button_type_button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ls-form__submit").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ls-form-indicator__item").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ls-form__submit").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".ls-form-indicator__item").text == "Connection failed"
  
