# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSU114():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.FIREFOX)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_sU114(self):
    self.driver.get("http://localhost:8081/projects/?page=1")
    self.driver.set_window_size(1120, 680)
    self.driver.find_element(By.CSS_SELECTOR, ".ls-projects-page__link:nth-child(2) .ls-project-card__title svg").click()
    self.driver.find_element(By.LINK_TEXT, "Settings").click()
    self.driver.find_element(By.LINK_TEXT, "Cloud Storage").click()
    element = self.driver.find_element(By.LINK_TEXT, "Machine Learning")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".ls-columns__item:nth-child(1) > .ls-storage-settings__controls > .ls-button").click()
    element = self.driver.find_element(By.NAME, "storage_type")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.NAME, "storage_type")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.NAME, "storage_type")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.NAME, "storage_type").click()
    self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(4)").click()
    self.driver.find_element(By.NAME, "path").click()
    self.driver.find_element(By.NAME, "password").send_keys("Thuytrang0304@")
    self.driver.find_element(By.NAME, "path").send_keys("20110753@student.hcmute.edu.vn")
    self.driver.find_element(By.NAME, "host").click()
    self.driver.find_element(By.NAME, "host").send_keys("8080")
    self.driver.find_element(By.CSS_SELECTOR, ".ls-button_type_button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ls-modal__body").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".ls-form-indicator__item").text == "Connection failed"
  
