name: Label Studio Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.10

      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create vaccination_tweets.csv
        run: |
          echo "col1,col2,col3" > vaccination_tweets.csv
          echo "data1,data2,data3" >> vaccination_tweets.csv

      - name: Install dependencies
        run: |
          pip install chromedriver-autoinstaller
          pip install selenium
          pip install webdriver_manager
          pip install ujson
          pip install requests_mock
          pip install boto3
          pip install moto
          pip install django
          pip install annoying
          pip install pandas
          pip install textblob
          pip install tweepy
          python -c "import pandas as pd; df = pd.DataFrame(['text']);"
          pip install pytest 
          pip install pytest-html

      - name: Run tests
        run: |
          python -m unittest discover -s Test -p 'test_*.py'
      - name: Upload Test Report
        run: |
          pytest --html=report.html
