name: Label Studio Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.10

      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create vaccination_tweets.csv
        run: |
          echo "col1,col2,col3" > vaccination_tweets.csv

      - name: Install dependencies
        run: |
          pip install chromedriver-autoinstaller
          pip install selenium
          pip install webdriver_manager
          pip install ujson
          pip install requests_mock
          pip install boto3
          pip install moto
          pip install django
          pip install annoying
          pip install pandas
          pip install textblob
          pip install tweepy
          pip install requests>=2.28
          pip install pytest 
          pip install pytest-html
          python -c "import pandas;df=pandas.DataFrame();df['text'] = ['Text1'].astpe(str)"

      - name: Run tests
        run:  pytest --html=report.html

      - name: Upload report artifact
        uses: actions/upload-artifact@v2
        with:
          name: Test Report
          path: report.html
