name: Label Studio Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.9

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install chromedriver-autoinstaller
          pip install selenium
          pip install webdriver_manager
          pip install ujson
          pip install requests_mock
          pip install boto3
          pip install moto
          pip install django
          pip install annoying
          pip install pandas
          pip install textblob
          pip install tweepy
          pip install requests>=2.28
          pip install pytest
          pip install pytest-html

      - name: Run tests
        run: pytest --junitxml=report.xml

      - name: Upload report artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Test Report
          path: report.xml
